---
# tasks file for splunk_forwarder

- block:

  - name: Validate required parameters and environment
    assert:
      that:
        - splunk_uf_install_url is defined
        - ansible_pkg_mgr is defined
        - ansible_pkg_mgr in ['yum', 'apt']

  - name: install the splunk deb package
    apt:
      deb: "{{ splunk_uf_install_url }}"
    when: ansible_pkg_mgr == 'apt'
    register: splunk_pkg_deb_install

  - name: install the splunk rpm package
    yum:
      name: "{{ splunk_uf_install_url }}"
    when: ansible_pkg_mgr == 'yum'
    register: splunk_pkg_rpm_install

  - name: add splunk user to the system group
    user:
      name: "{{ splunk_uf_system_user }}"
      groups: "{{ splunk_uf_system_group }}"
      append: yes

  - name: store package installation result as boolean var
    set_fact:
      splunk_pkg_install: splunk_pkg_deb_install.changed or splunk_pkg_rpm_install.changed

  become: yes
  tags:
    - install

- name: install inputs.conf via template
  template:
    src: "{{ splunk_uf_inputs_conf_template }}"
    dest: /opt/splunkforwarder/etc/system/local/inputs.conf
    owner: "{{ splunk_uf_system_user }}"
    group: "{{ splunk_uf_system_group }}"
    mode: 0644
  when: splunk_uf_inputs_conf_template | default(false)
  notify:
    - restart splunkforwarder
  tags:
    - inputs

- name: install outputs.conf via template
  template:
    src: "{{ splunk_uf_outputs_conf_template }}"
    dest: /opt/splunkforwarder/etc/system/local/outputs.conf
    owner: "{{ splunk_uf_system_user }}"
    group: "{{ splunk_uf_system_group }}"
    mode: 0644
  when: splunk_uf_outputs_conf_template | default(false)
  notify:
    - restart splunkforwarder
  tags:
    - outputs
